apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Oracle-Service-Bus-OSB12C
  description: TallerSoa
  annotations:
    github.com/project-slug: crlsquilumba/Oracle-Service-Bus-OSB12C
    github.com/branch-count: "1"
    github.com/has-gitflow: "false"
    github.com/default-branch: "main"
  links:
    - url: https://github.com/crlsquilumba/Oracle-Service-Bus-OSB12C/tree/main
      title: "✅ main — producción"
      icon: github
spec:
  type: library
  lifecycle: experimental
  owner: user:default/guest
